server:
  port: 8091
  application:
    name: xfg-dev-tech-zookeeper

# zookeeper 自定义链接配置
zookeeper:
  sdk:
    config:
      connect-string: 192.168.1.103:2181
      base-sleep-time-ms: 1000
      max-retries: 3
      session-timeout-ms: 18000
      connection-timeout-ms: 30000

# 日志
logging:
  level:
    root: debug
  config: classpath:logback-spring.xml